---
# tasks file for ansible-role-mysql

- name: Run if OS is Debian or Ubuntu
  ansible.builtin.include_tasks: debianmysql.yml
  when: ansible_facts['os_family'] == "Debian"
  tags: ubuntu-mysql

- name: Run if OS is RedHat family (CentOS/Rocky/Alma)
  ansible.builtin.include_tasks: centosmysql.yml
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution'] in ['CentOS', 'Rocky', 'AlmaLinux', 'RedHat']
  tags: redhat-mysql

- name: Secure MySQL Installation
  ansible.builtin.include_tasks: mysqlsecure.yml
  tags: mysql-secure